services:
  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: valkey

    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      [
        "valkey-server",
        "--requirepass", "pass333",
        "--appendonly", "yes",
        "--appendfsync", "everysec",
        "--save", "60", "1000",
        "--maxmemory", "256mb",
        "--maxmemory-policy", "allkeys-lru",
        "--tcp-keepalive", "300"
      ]

    volumes:
      - valkey_data:/data

    networks:
      - internal_net

volumes:
  valkey_data:

networks:
  internal_net: